version: "3.7"

networks:
  network-branas:
    driver: bridge

services:
  database_branas:
    image: postgres
    container_name: database_branas
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    volumes:
      - pgsql:/var/lib/postgresql/data
    networks:
      - network-branas

  app:
    build: .
    container_name: branas
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    command: npm run dev
    environment:
      - DATABASE_URL=database_branas
    networks:
      - network-branas
    depends_on:
      - database_branas
    links:
      - database_branas

volumes:
  pgsql:
    driver: local
